stages:
  data_ingestion:
    cmd: python src/data_ingestion.py
    deps:
      - src/data_ingestion.py
    outs:
      - data/raw

  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
    outs:
      -data/processed
  
  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
    outs:
      -data/features

  model_building:
    cmd : python src/model_building.py
    deps:
      - src/model_building.py
    outs:
      -data/models


  model_evaluation:
    cmd : python src/model_evaluation.py
    deps:
      - src/model_evaluation.py
    outs:
      -data/evaluation
