artifact_location: file:///E:/pandey/learning/data%20science/9.mlops/MLOPS_Tutorial/2.frameworks/1.mlflow%20by%20Manual_Gill/try/mlruns_folder/830581414928407917
creation_time: 1756531350940
experiment_id: '830581414928407917'
last_update_time: 1756531350940
lifecycle_stage: active
name: first_experiment_using_MLFLOW_SDK
