artifact_location: file:///E:/pandey/learning/data%20science/9.mlops/MLOPS_Tutorial/2.frameworks/1.mlflow%20by%20Manual_Gill/try/mlruns_folder/0
creation_time: 1756531350912
experiment_id: '0'
last_update_time: 1756531350912
lifecycle_stage: active
name: Default
